---
title: 'HW #5'
author: "Zhu_Xinying_R"
date: "2016/10/13"
output: html_document
---

```{r}
#1. Print to the console all methods and attributes associates with a dataframe. Write code to determine the number of columns in a dataframe
library('ggplot2') #using the package ggplot2 in R into library function
class(diamonds)#using the class function to get the class of diamonds
methods(class=class(diamonds)[3])#using the mothods function. also, there are three classes in diamonds.
attributes(diamonds)#using the attributes function with the dataframe to get all attributes.
ncol(diamonds)#count the number of columns
```

```{r}
#2. Write code to determine how many rows are in a dataframe
nrow(diamonds) #count the number of rows
```

```{r}
#3. Write code to extract the column names from a dataframe and print the names of the columns (one per line) to the console.
colnames(diamonds) #extract the column names
```

```{r}
#4. Write code to determine the type of each column (numeric, factor, logical,etc.). Print the type of each column to the console.
lapply(diamonds,class) #using the lapply function to determine the type of each column
```

```{r}
#5. Write code that will loop through any dataframe and calculate the mean of every numeric column. Label the output with the name of the column.
diamonds_num<-diamonds[sapply(diamonds,is.numeric)]#using the sapply function to find numeric colume
lapply(diamonds_num,mean,na.rm=TRUE)#using lapply function to get the mean of every numeric column

```

```{r}
#6. Write code that will loop through any dataframe and create a frequency table for every factor column. Label the output with the name of the column.
summary(diamonds[sapply(diamonds,is.factor)])#using the sapply with every factor column, then using summary function to get a frequency table for every factor column

```

```{r}
#7. Write code that will loop through any dataframe and determine the number of rows containing NA (missing value) in each column and the percentage of rows containing an NA in any of the columns. HINT: In a single row, zero or more columns may contain an NA. For the percentage of rows containing NA in any column, do not double count NA in rows that contain more than one column with an NA. Print the results to the console.
apply(sapply(diamonds,is.na),2,sum)#using apply function extract the number of rows containing NA(missing value) in each column
sum(rowSums(is.na(diamonds))>0)/nrow(diamonds) #using sum function to get the percentage of rows containing an NA in any of the columns

```




