---
title: "Zhu_Xinying_HW6.R"
author: "Zhu_Xinying_R"
date: "2016/10/20"
output: html_document
---

library(ggplot2) #require ggplot2 in R library to use.
data("diamonds") #using the diamonds dataset
```{r}
#1. Create a histogram for every numeric column in the diamonds dataset.
library(ggplot2) #require ggplot2 in R library to load.
data("diamonds") #using the diamonds dataset
histcarat<-ggplot(diamonds,aes(carat))#create the carat histogram 
histcarat+geom_histogram(bins=60)+ggtitle("Carat Histogram")+xlim(0,3)#plot the carat histogram,also named Carat Histogram. using xlim to remove the outliers that out of 0 to 3.

histdepth<-ggplot(diamonds,aes(depth))#create the depth histogram
histdepth+geom_histogram(bins=60)+ggtitle("Depth Histogram")+xlim(50,70)#plot the depth histogram,also named Depth Histogram. using xlim to remove the outliers that out of 50 to 70.

histtable<-ggplot(diamonds,aes(table))#create the table histogram
histtable+geom_histogram(bins=40)+ggtitle("Table Histogram")+xlim(50,70)#plot the table histogram,also named Table Histogram. using xlim to remove the outliers that out of 50 to 70.

histprice<-ggplot(diamonds,aes(depth))#create the price histogram
histprice+geom_histogram(bins=60)+ggtitle("Price Histogram")#plot the price histogram,also named Price Histogram. 

histx<-ggplot(diamonds,aes(x))#create the x histogram
histx+geom_histogram(bins=60)+ggtitle("X Histogram")+xlim(3,10)#plot the x histogram,also named X Histogram. using xlim to remove the outliers that out of 3 to 10.

histy<-ggplot(diamonds,aes(y))#create the y histogram
histy+geom_histogram(bins=180)+ggtitle("Y Histogram")+xlim(3,10)#plot the y histogram,also named Y Histogram. using xlim to remove the outliers that out of 3 to 10.

histz<-ggplot(diamonds,aes(z))#create the z histogram
histz+geom_histogram(bins=60)+ggtitle("Z Histogram")+xlim(2,6)#plot the z histogram,also named Z Histogram. using xlim to remove the outliers that out of 2 to 6.
```

```{r}
#2. Create a simple scatter plot of Weight (“Carat”) and Price using Color (the “Color” column in the diamonds dataframe) as a facet.
scatplot<-ggplot(diamonds,aes(x=carat,y=(price)),colour=color)
scatplot<-scatplot+geom_point()+ggtitle("Diamonds - Weight to Price by Color") + xlab("Weight")
scatplot<-scatplot+ylab("Price")+labs(colour="factor(color)")
print(scatplot)#plot the "price and weight" on scatter plot,x axis is carat, y axis is price. and colour to color, using color as facet. using geom_point for scatter plot.

```

```{r}
#3. Let’s remove the non-linearity and replot. Think about transforming both price and weight. Given that we are working with dollars (Price); the first transformation we might try is the natural log. Add the transformed columns to the dataframe and replot.
scatlin<-ggplot(diamonds,aes(x=log(carat),y=log(price),colour=color))
scatlin<-scatlin+geom_point()+ggtitle("Diamonds-Weight to Price (Liner)")+xlab("Weight")
scatlin<-scatlin+ylab("Price")+labs(colour="factor(color)")
print(scatlin)#plot"log(carat) and log(price)" on scatter plot. x axis is log(carat), y axis is log(price). using color as facet, and geom_point for scatter plot.
```

```{r}
#4. Remove the linear trend (create a linear model and use the transformed weight on the x-axis and the residuals on the y-axis). If there is a relationship that can be modeled with a linear regression model, then the residuals should be randomly distributed. The resulting plot visually indicates there is possibly some heteroscedasticity to manage.
lmfit<-lm(log(price)~log(carat),data=diamonds)#get linear model of y = log(price) to x = log(carat) 
residual<-resid(lmfit)#define residual to extract residuals from linear model
scat<-ggplot(diamonds,aes(x=log(carat),y=residual,colour=color))#define scat to be a ggplot object. x axis is log(carat), y axis is residual.colour to color.
scat<-scat+geom_point()+ggtitle("Diamonds-Weight to Price by Color")+xlab("Weight") #plot the graph, and change the title, x axis, y axis. using geom_point for the scatter plot, and kay as appropriate.
scat<-scat+ylab("Price Residuals")+labs(colour="factor(color)")+theme(legend.position="top")#move the legend to the top of the scatter plot
print(scat)
```